name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: نصب Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.4'
      
      - name: دریافت وابستگی‌ها
        run: flutter pub get
      
      - name: بیلد APK
        run: flutter build apk --release
      
      - name: آپلود APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
