name: Build Android APK

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: دریافت کدها
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: نصب Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: نصب Android SDK
        uses: android-actions/setup-android@v3

      - name: نصب Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: دریافت وابستگی‌ها
        run: flutter pub get

      - name: بیلد APK
        run: flutter build apk --release

      - name: آپلود APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
